# This worflow is primarily for platform/devops tools that need to be deployed into K8s cluster
# or tools that don't belong to Terraform
name: 'Workflow - Deploy Platform Tools'

on:
  push:
    branches:
      - feature/**
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  ENVIRONMENT_STAGE: "dev"

jobs:
  deploy-platform-tools:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ env.AWS_REGION }}

      # Official installation instructions from https://eksctl.io/installation/
      - name: Install eksctl
        run: |
            ARCH=amd64
            PLATFORM=$(uname -s)_$ARCH
            curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
            
            tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
            sudo mv /tmp/eksctl /usr/local/bin
            eksctl version
    
      # Create EKS cluster with CloudFormation
      # both AWSReservedSSO_Administrator-* role and role running this job should get full access to this EKS cluster
      - name: Create EKS Cluster with CloudFormation
        run: |
            SSO_ADMIN_ROLE=$(aws iam list-roles --query "Roles[?starts_with(RoleName, 'AWSReservedSSO_Administrator')].Arn" --output text)
            make cluster name=temporary-eks-cluster-${ENVIRONMENT_STAGE} version=1.28 role=$SSO_ADMIN_ROLE
        working-directory: ./eks-cloudformation

      # Login to EKS, make sure to switch to the permanent cluster created with terraform once it's up
      - name: Login to EKS - update kubeconfig
        run: aws eks update-kubeconfig --name temporary-eks-cluster-${ENVIRONMENT_STAGE} --region $AWS_REGION

      # Add deployment steps for each tool below
      # Example for a tool like Cluster Autoscaler
      - name: Deploy Cluster Autoscaler
        run: |
            echo "Deploy Cluster Autoscaler steps go here"

      # Example for a tool like EKS Logging
      - name: Deploy EKS Logging
        run: |
            echo "Deploy EKS Logging steps go here"

      # Repeat for each additional tool...
      # Example: Deploy External DNS
      # Example: Setup K8s User Roles

      - name: Finalize Deployment
        run: |
            echo "Final deployment steps and cleanup"

